version: "3.7"
services:
  app:
    build:
      args:
        user: rudra
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: blood_web
    container_name: blood-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bloodnet

  db:
    image: mysql:5.7
    container_name: bloodapp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - bloodnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bloodapp-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_DATABASE: ${DB_DATABASE}
    ports:
      - 8080:80
    networks:
      - bloodnet

  nginx:
    image: nginx:alpine
    container_name: blood_web-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - bloodnet

networks:
  bloodnet:
    driver: bridge
